name: CI checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]    # <-- заменили 3.1 на 3.10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  # <-- здесь тоже

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy pytest

      - name: Black check
        run: black --check .

      - name: Flake8 lint
        run: flake8 .

      - name: MyPy static types
        run: mypy .

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
