name: CI checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # dev-зависимости для линтинга/тестов
          pip install black flake8 mypy pytest

      - name: Black check
        run: |
          black --check .

      - name: Flake8 lint
        run: |
          flake8 .

      - name: MyPy static types
        run: |
          mypy .

      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q