# .github/workflows/docker-publish.yml
name: CI/CD Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read      # читать код
  packages: write     # пушить пакеты в GHCR
  id-token: write     # если нужен OIDC

jobs:
  # 1) Прогоняем тесты
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

  # 2) Билдим и пушим Docker-образ, но только если тесты прошли
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (optional for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/akitobora/uks_checker-free-flats-bot:latest
            ghcr.io/akitobora/uks_checker-free-flats-bot:${{ github.sha }}
            ghcr.io/akitobora/uks_checker-free-flats-bot:${{ github.ref_name }}

      - name: Image details
        if: success()
        run: |
          echo "→ latest: ghcr.io/akitobora/uks_checker-free-flats-bot:latest"
          echo "→ sha:    ghcr.io/akitobora/uks_checker-free-flats-bot:${{ github.sha }}"
          echo "→ ref:    ghcr.io/akitobora/uks_checker-free-flats-bot:${{ github.ref_name }}"
