name: Build, Push and Deploy to Yandex Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Yandex Container Registry
      run: echo "${{ secrets.YC_CR_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: cr.yandex/crpkei0r7il07rbflqkj/uks_checker:latest

    - name: Deploy to Yandex Cloud VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.YC_VM_HOST }}
        username: ${{ secrets.YC_VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker pull cr.yandex/<your-registry-id>/uks_checker:latest
          docker stop uks_checker || true
          docker rm uks_checker || true
          docker run -d --name uks_checker cr.yandex/crpkei0r7il07rbflqkj/uks_checker:latest
