# .github/workflows/docker-publish.yml
name: CI/CD Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN:          fake_token
      CHAT_ID:            "0"
      PAGE_URL:           "https://example.com/pdf"      # для PDF
      NEWS_PAGE_URL:      "https://example.com/news"     # для новостей
      BASE_URL:           "https://example.com"
      STATE_FILE:         "last.json"
      CHECK_EVERY_MINUTES: "1"
      NEWS_CHECK_INTERVAL: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/akitobora/uks_checker-free-flats-bot:latest
  deploy:
      needs: build-and-push
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to VM via SSH
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: ${{ secrets.VM_HOST }}
            username: ${{ secrets.VM_USER }}
            key: ${{ secrets.VM_SSH_KEY }}
            port: 22
            script: |
              # Вытащить свежий образ
              docker pull ghcr.io/akitobora/uks_checker-free-flats-bot:latest
              # Остановить старый
              docker stop uks_checker-free-flats-bot || true
              docker rm   uks_checker-free-flats-bot || true
              # Запустить новый
              docker run -d \
                --name uks_checker-free-flats-bot \
                --restart=unless-stopped \
                ghcr.io/akitobora/uks_checker-free-flats-bot:latest