name: Build, Push and Deploy to Yandex VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Yandex Container Registry
      run: echo "${{ secrets.YC_CR_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

    - name: Build and push image to YCR
      run: |
        docker build -t cr.yandex/ru-central1/crpkei0r7il07rbflqkj/uks-checker:latest .
        docker push cr.yandex/ru-central1/crpkei0r7il07rbflqkj/uks-checker:latest

    - name: Deploy to Yandex VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.YC_VM_HOST }}
        username: ${{ secrets.YC_VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd uks_checker
          docker login -u oauth -p ${{ secrets.YC_CR_TOKEN }} cr.yandex
          docker compose pull
          docker compose up -d
