# .github/workflows/docker-publish.yml
name: CI/CD Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN:          fake_token
      CHAT_ID:            "0"
      PAGE_URL:           "https://example.com/pdf"      # для PDF
      NEWS_PAGE_URL:      "https://example.com/news"     # для новостей
      BASE_URL:           "https://example.com"
      STATE_FILE:         "last.json"
      CHECK_EVERY_MINUTES: "1"
      NEWS_CHECK_INTERVAL: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name : Install library in dev mode
        run: pip install -e 

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/akitobora/uks_checker-free-flats-bot:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (для доступа к docker-compose.yml, если нужно)
        uses: actions/checkout@v4
        # либо пропустите, если на сервере compose-файл уже лежит

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM via SSH and docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd /uks_checker
            # подтягиваем новую версию образа
            docker compose pull free-flats-bot
            # пересоздаём контейнер без даунтайма
            docker compose up -d --no-deps --remove-orphans free-flats-bot
          EOF
